### ISSUE TITLE
Font break on AWS EC2 instance

### ISSUE THREAD

**Issue by myungwoo** [ioi/translation-old#4]
There is a font break on AWS EC2 instance.

As showon as below.
![2016-02-08 2 40 48](https://cloud.githubusercontent.com/assets/9026019/12879197/139d469e-ce73-11e5-9cb8-68653f453f5a.png)

It occurs because of Server OS.
So it can be sovled by installing ubuntu-desktop package.
`sudo apt-get install ubuntu-desktop`

**Comment by myungwoo** [comment]
Another simple solution

```
sudo apt-get install fontconfig fontconfig-config fonts-dejavu-core fonts-droid \
  fonts-freefont-ttf fonts-kacst fonts-kacst-one fonts-khmeros-core fonts-lao \
  fonts-liberation fonts-lklug-sinhala fonts-nanum fonts-opensymbol \
  fonts-sil-abyssinica fonts-sil-padauk fonts-takao-pgothic fonts-thai-tlwg \
  fonts-tibetan-machine fonts-tlwg-garuda fonts-tlwg-kinnari fonts-tlwg-loma \
  fonts-tlwg-mono fonts-tlwg-norasi fonts-tlwg-purisa fonts-tlwg-sawasdee \
  fonts-tlwg-typewriter fonts-tlwg-typist fonts-tlwg-typo fonts-tlwg-umpush \
  fonts-tlwg-waree -y
```

**Comment by dannvix** [comment]
Thank you for providing a nice solution @myungwoo . I'll add this to README.
